### ISSUE TITLE
App switches the power even if speaker not connected

### ISSUE THREAD

**Issue by alperenkaplan** [Shingyx/BoomSwitch#1]
When I want to turn on the device but don't realize that it's already on, just not connected, app turns the device off anyways. Can you make it so it connects to the speaker instead of switching it off when the speaker is on but not connected. I tried to contribute but I don't write java, still tried though. However I got lost in GATT etc. Just couldn't figure out how the function actually switches the power on and off

**Comment by Shingyx** [comment]
Hi! Thanks for reporting this issue. I've reproduced this behaviour and will start looking into it soon.

FYI, the code which initiates the switching is located here:
https://github.com/Shingyx/BoomSwitch/blob/bd021426989e9af2d592cc0745ad9fbfd2f7c98e/app/src/main/java/com/github/shingyx/boomswitch/data/BoomClient.kt#L180-L194

**Comment by Shingyx** [comment]
I've made a fix which works just fine on my BOOM 3, but I'd like to test it some more before making a public release with the changes on Google Play.

The fix is available on the [connect-if-on-but-disconnected](https://github.com/Shingyx/BoomSwitch/tree/connect-if-on-but-disconnected) branch if you want to test it yourself as well.

Assuming the changes are all good, I'll release the changes some time this week.

**Comment by Shingyx** [comment]
Version 1.1 is now being processed by Google Play and will be available soon. Please let me know if it fixes your issue. Cheers.

**Comment by alperenkaplan** [comment]
Thanks for the fix. App now works as expected.
