### ISSUE TITLE
Feature Request: Toggle the Remote Activation Feature

### ISSUE THREAD

**Issue by Zeik0s** [Shingyx/BoomSwitch#7]
Hi @Shingyx, thx for creating this separate App. 
Could you integrate the Function for turning off the Remote Activation Function? UE decided to remove the Function from the official App, so it would be a great possibility for bringing it back here. 

I understand, that some people are appreciating the Feature, but for me, the Speakers are emptying to much energy in Standby, that's why i want to have the functionality back as a User. 
Is that feasible?

**Comment by Shingyx** [comment]
I apologise for not getting back until now... This has fallen well off my radar.

I suspect "turning off remote activation" really just disables the speaker's Bluetooth LE (Low Energy) server while it is not powered on. So going by memory, setting the `powerByte` to `0` inside this method should do it.

https://github.com/Shingyx/BoomSwitch/blob/08efa3993bd798fd6a531b638d7ae174261ff86e/app/src/main/java/com/github/shingyx/boomswitch/data/BoomClient.kt#L228-L256

However, I sense that there are many users who are experiencing issues with the app failing to connect to the speaker using Bluetooth LE. This is going by Google reviews, other GitHub issues, and the emails I have received. 

Because of this, I do not feel comfortable publishing a new version with this change, even hidden away as an "advanced feature", because it intentionally disables the main functionality of BOOM Switch, by disabling the speaker's Bluetooth LE server which this app heavily relies on.

I am going to close this issue, partly because it's very old, but please reply if you would still like this functionality _in general_. I could create something like a separate "BOOM No Switch" app which intentionally disables the Bluetooth LE server, to be run once and then uninstalled.

**Comment by Zeik0s** [comment]
I would still like this feature in general @Shingyx, because the UE App provided this feature in the past and ditched it. My request for this is i don't use the remote toggle switch at all and hence the Bluetooth LE server still draws more power of my two speakers, which i have to recharge more often of course.

**Comment by Shingyx** [comment]
Sorry for the long delay. I've created a build which _should_ disable the remote power feature but it has some caveats, at least on my BOOM 3. This build renames the app to "BOOM Disable Switch" to avoid confusion.

- After using the app to disable the remote power feature, attempting to disable again gives a Bluetooth LE connection error, suggesting it disabled the feature successfully.
- Once disabled, pressing the power button on the speaker once will not turn it on. Instead, it re-enables the remote power feature. Pressing the power button _again_ will turn on the speaker.
- Afterwards, you'll need to use the app again to disable the remote power feature.

You can find the apk created by [GitHub Actions here](https://github.com/Shingyx/BoomSwitch/actions/runs/6367170877), but I've also attached it to this comment for convenience and for when the artifact expires: [boom-switch-debug-apk.zip](https://github.com/Shingyx/BoomSwitch/files/12775890/boom-switch-debug-apk.zip)

See the [`disable-remote-power`](https://github.com/Shingyx/BoomSwitch/tree/disable-remote-power) branch for source code if interested. However, I am still not comfortable building this feature into the main app as explained in my previous comment. I might reconsider if this issue gets a bit more traction from more users.

I hope this helps for now. 🙂
